# this machine readable TOML file defines the default configuration for the extra-solar camera coronagraph
[Detector]
CMOS_QE = "sensors/ZWO_ASI6200MM/ZWO_ASI6200MM_Pro_QE_curve.fits"
CMOS_dark = "sensors/ZWO_ASI6200MM/ZWO_ASI6200MM_Pro_Dark_Current_vs_Sensor_Temperature.csv"
CMOS_gain = 4
CMOS_read = 3  # [electrons]
CMOS_well = 50000 # [electrons]

[Pupils]  # This should moved to stp_reference_data
D_chA_clear_OD = '2.430m' # Diameter of pupil on M1 for coronagraph channel A from optical design (same commit as this change)
D_chB_clear_OD = '1.195m' # Diameter of pupil on M1 for coronagraph channel B from optical design (same commit as this change)

[sim_settings]  # settings for simulation tool
npix = 4096 # number of pixels per frame
beamrad = 0.4 # beam radius


[Layout] # Default optical layout
# Naming follows mechanical layout diagram in the coronograph guide (stp202310_0002). Currently figure 4.3
OAP1_mech_OD = '50e-3m'
OAP1_clear_OD = '40e-3m' # 80% CA assumed
OAP1_rms_surface = '2.0e-9m' 
OAP1_B = 10 # cycles/m
OAP1_C = 2.65 # power law exponent
OAP_refl = "coatings/AlMgF2_curve.csv"
DM_refl = "coatings/bmc_dm_au.csv"

FOLD1_mech_OD = '50e-3m'
FOLD1_clear_OD = '40e-3m' # 80% CA assumed
FOLD1_rms_surface = '2.0e-9m' 
FOLD1_B = 10 # cycles/m
FOLD1_C = 2.65 # power law exponent

OAP2A_mech_OD = '25e-3m'
OAP2A_clear_OD = '20e-3m' # 80% CA assumed
OAP2A_rms_surface = '2.0e-9m' 
OAP2A_B = 10 # cycles/m
OAP2A_C = 2.65 # power law exponent

OAP3A_mech_OD = '25e-3m'
OAP3A_clear_OD = '20e-3m' # 80% CA assumed
OAP3A_rms_surface = '2.0e-9m' 
OAP3A_B = 10 # cycles/m
OAP3A_C = 2.65 # power law exponent

OAP4_mech_OD = '25e-3m'
OAP4_clear_OD = '20e-3m' # 80% CA assumed
OAP4_rms_surface = '5.0e-9m' 
OAP4_B = 10 # cycles/m
OAP4_C = 2.65 # power law exponent

FOLD2_mech_OD = '50e-3m'
FOLD2_clear_OD = '40e-3m' # 80% CA assumed
FOLD2_rms_surface = '2.0e-9m' 
FOLD2_B = 10 # cycles/m
FOLD2_C = 2.65 # power law exponent

OAP5_mech_OD = '25e-3m'
OAP5_clear_OD = '20e-3m' # 80% CA assumed
OAP5_rms_surface = '5.0e-9m' 
OAP5_B = 10 # cycles/m
OAP5_C = 2.65 # power law exponent

OAP6_mech_OD = '25e-3m'
OAP6_clear_OD = '20e-3m' # 80% CA assumed
OAP6_rms_surface = '5.0e-9m' 
OAP6_B = 10 # cycles/m
OAP6_C = 2.65 # power law exponent

OAP7_mech_OD = '25e-3m'
OAP7_clear_OD = '20e-3m' # 80% CA assumed
OAP7_rms_surface = '5.0e-9m' 
OAP7_B = 10 # cycles/m
OAP7_C = 2.65 # power law exponent

OAP8_mech_OD = '25e-3m'
OAP8_clear_OD = '20e-3m' # 80% CA assumed
OAP8_rms_surface = '5.0e-9m' 
OAP8_B = 10 # cycles/m
OAP8_C = 2.65 # power law exponent

SPHR1_mech_OD = '25e-3m'
SPHR1_clear_OD = '20e-3m' # 80% CA assumed
SPHR1_rms_surface = '5.0e-9m' 
SPHR1_B = 10 # cycles/m
SPHR1_C = 2.65 # power law exponent

OAP9_mech_OD = '25e-3m'
OAP9_clear_OD = '20e-3m' # 80% CA assumed
OAP9_rms_surface = '5.0e-9m' 
OAP9_B = 10 # cycles/m
OAP9_C = 2.65 # power law exponent

# LLOWFS OAP
OAPL_mech_OD = '25e-3m'
OAPL_clear_OD = '20e-3m' # 80% CA assumed
OAPL_rms_surface = '5.0e-9m' 
OAPL_B = 10 # cycles/m
OAPL_C = 2.65 # power law exponent
